### ISSUE TITLE
timestamp is not UNIX time (x1000 value returned)

### ISSUE THREAD

**Issue by momijiame** [bitbankinc/bitbank-api-docs#10]
`timestamp` parameters are not UNIX time.
Actually, they are 1000 times (milliseconds) of UNIX time.

There are two possibilities:

1. implementation is correct / documentation is wrong
2. documentation is correct / implementation is wrong

## Expected Behavior

- If (1) is correct
  - need to fix the representation of the document (1000 times)
- If (2) is correct
  - need to fix implementation (divide by 1000)

## Current Behavior

Returned x1000 value of UNIX time.

## Steps to Reproduce

1.

```bash
$ curl -s "https://public.bitbank.cc/btc_jpy/ticker" | jq ".data.timestamp"
1581669923800
$ date +%s
1581669928
```

2.

```bash
$ BITBANK_TIMESTAMP=$(curl -s "https://public.bitbank.cc/btc_jpy/ticker" | jq ".data.timestamp")
$ python -c "from datetime import datetime; print(datetime.fromtimestamp($BITBANK_TIMESTAMP))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: year 52091 is out of range
```

3.

```bash
$ python -c "from datetime import datetime; print(datetime.fromtimestamp($(($BITBANK_TIMESTAMP / 1000))))"
2020-02-14 17:45:51
```

**Comment by daiki-ojima** [comment]
@momijiame 

Thank you for the bug report.

> 1. implementation is correct / documentation is wrong

This is correct.
Fix documentation ([update 2020-02-17](https://github.com/bitbankinc/bitbank-api-docs/commit/6daa62590da9eebf178f1b3d3d9a2cd2680d04fe)).
