### ISSUE TITLE
マルチネットワーク対応に伴いAPIのレスポンスに変更があったが、ドキュメントに反映されていない。

### ISSUE THREAD

**Issue by niwatako** [bitbankinc/bitbank-api-docs#100]
[マルチネットワーク対応](https://blog.bitbank.cc/354110163/) に伴い、ドキュメントの記載が古くなっている。

## Expected Behavior
Private REST API `GET /user/assets` （アセット一覧）の[ドキュメント](https://github.com/bitbankinc/bitbank-api-docs/blob/master/rest-api_JP.md#%E3%82%A2%E3%82%BB%E3%83%83%E3%83%88%E4%B8%80%E8%A6%A7%E3%82%92%E8%BF%94%E3%81%99)について、

パラメータ `withdrawal_fee` の型の記載を `{ "min": String, "max": String }` に改める。

さらに、暗号資産の場合に返されるパラメータ `network_list` について追記する。
Name: `network_list `
Type: `[{"asset": string, "network": string, "stop_deposit": boolean, "stop_withdrawal": boolean, "withdrawal_fee": string}]`

## Current Behavior

パラメータ `withdrawal_fee` は暗号資産の場合 string と記載されている。
また、 `network_list` パラメータについては記載がない。

## FYI
入出金に関連して従来アドレスを返していたようなエンドポイントについては、ネットワーク情報も返すようになっているのではないかと思いますので、合わせて確認が必要かと思います。
`GET /user/deposit_history`, `GET /user/withdrawal_account`,  `GET /user/withdrawal_history`

**Comment by soichirokodama** [comment]
ご指摘ありがとうございます。
こちらの件に関しては認識しており、システムリリースとDocsへの反映のタイミングがずれてしまい申し訳ございません。
以下のp-rで修正を反映しております。

https://github.com/bitbankinc/bitbank-api-docs/pull/101

**Comment by niwatako** [comment]
修正済みということですので、クローズさせていただきます。
ご対応ありがとうございます。
