### ISSUE TITLE
ペア一覧に記載されたQuote assetとBase assetの見出しが逆である

### ISSUE THREAD

**Issue by niwatako** [bitbankinc/bitbank-api-docs#104]
## Expected Behavior

XXX/YYYのペアがあるとき、
XXXがBase、YYYがQuoteである。

## Current Behavior

ドキュメントの[Pair一覧](https://github.com/bitbankinc/bitbank-api-docs/blob/master/pairs.md)のTableの見出しは逆になっており、
たとえばbtc_jpyは、btc/jpyのペアであるが、
btcがQuote asset、jpyがBase assetと記載されている。
![スクリーンショット 2023-12-05 13 27 28](https://github.com/bitbankinc/bitbank-api-docs/assets/1546218/9d287512-b69a-4a7d-89fe-f355eafc1c10)

なお銘柄詳細( `https://api.bitbank.cc/v1/spot/pairs` )の実装は正しく、
`btc_jpy`は `"base_asset": "btc"` `"quote_asset": "jpy"` の結果を返す。
![スクリーンショット 2023-12-05 13 23 27](https://github.com/bitbankinc/bitbank-api-docs/assets/1546218/61e0811b-7133-4bc7-99d7-68145b8d899e)

**Comment by soichirokodama** [comment]
ご指摘いただきありがとうございます。
おっしゃる通りBaseとQuoteが逆になっていますね。
pull-requestも作成いただいているようなので、確認させていただきます。

**Comment by soichirokodama** [comment]
こちらpull requestもマージいたしました。
ご対応いただきありがとうございます。
