### ISSUE TITLE
EIO4 behaviour

### ISSUE THREAD

**Issue by LemonPepperSeasoning** [bitbankinc/bitbank-api-docs#108]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior & Current Behavior

> In EIO=4, you must send 3(pong frame) that is sent every pingInterval milliseconds when you receive 2(ping frame)

Currently, in EIO=4, server sends `2 (ping frame)` using `op_code=1, frame.data=b'2'`. (ie, it is using `OPCODE_TEXT`)

Should't it be instead using `OPCODE_PING` (`op_code=9, frame.data=b'2'`)?

## Steps to Reproduce
```
$ wscat -c 'wss://stream.bitbank.cc/socket.io/?EIO=4&transport=websocket'
< 0{"sid":"OzbfYTGSVEbgAPS4fLbh","upgrades":[],"pingInterval":25000,"pingTimeout":20000,"maxPayload":1000000}
> 40
> 42["join-room","ticker_btc_jpy"]
...
< 2
...
```

## Context (Environment)
Found EIO4 websocket stream had unique behaviour. Ref: https://github.com/bitbankinc/bitbank-api-docs/issues/77

**Comment by koiibb** [comment]
Thank you for your opinion!

The Websocket heartbeat protocol and Socket.IO heartbeat mechanism are separate.

socketio (engineio v4) heartbeat mechanism: https://socket.io/docs/v4/engine-io-protocol/#heartbeat

So you need to send 2 (ping message) message (not `OPCODE_PING` frame) based on Socket.IO heartbeat protocol
