### ISSUE TITLE
Post-Only order

### ISSUE THREAD

**Issue by tacotokyo** [bitbankinc/bitbank-api-docs#12]
Currently taker pays 0.12% fee for trading. The fee is a huge cost if you wanted to be a maker and there is no way to prevent this situation. It would be great if you can add Post-Only order option(a.k.a GoodTillCrossing or GTX) in order to prevent this.

https://bitbank.cc/docs/fees/

**Comment by anhnguyenhoang** [comment]
totally agree. Post-only is a basic feature. most exchanges support it

**Comment by tacotokyo** [comment]
Finally this feature has been implemented. Good job!

https://blog.bitbank.cc/202104_03/
