### ISSUE TITLE
Fetch trade history only returns 500 records

### ISSUE THREAD

**Issue by newbdez33** [bitbankinc/bitbank-api-docs#19]
Fetch trade history
GET /user/spot/trade_history

This api  only returns 500 records even I specified a "count" param.

## Expected Behavior
It should returns the number of "count" param.

## Current Behavior
It only returns 500 records.

## Steps to Reproduce
1. call this api with more then 500 records history pair

**Comment by mojamonja** [comment]
@newbdez33 
Thanks for creating the issue!

As I recently updated the docs, the `count` parameter of GET /user/spot/trade_history only accepts up to 1000.
And if you specify more than 1000, it will not return as much as you specified.

I think you did specify more than 1000 for `count`.
Could you try 1~1000 for `count` parameter?

**Comment by newbdez33** [comment]
Got it. Thank you @mojamonja !
