### ISSUE TITLE
Websocket request example.

### ISSUE THREAD

**Issue by henritoivar** [bitbankinc/bitbank-api-docs#2]
Hi. I could not find from the documentation what is the format to subscribe to a channel.

Could you please provide an example payload.

**Comment by daiki-ojima** [comment]
Our stream api is implemented with socket.io.
And `EIO` version must be specified.
There is subscribe sample with [wscat](https://github.com/websockets/wscat).

```bash
# depth whole
$ npx wscat -c 'wss://stream.bitbank.cc/socket.io/?EIO=3&transport=websocket'
< 40
> 42["join-room", "depth_whole_btc_jpy"]

# depth diff
$ npx wscat -c 'wss://stream.bitbank.cc/socket.io/?EIO=3&transport=websocket'
< 40
> 42["join-room", "depth_diff_btc_jpy"]
```

Will be documented as soon as possible.

**Comment by daiki-ojima** [comment]
Published sample of websocket request.
Please refer to the following:
https://github.com/bitbankinc/bitbank-api-docs/blob/master/public-stream.md

**Comment by henritoivar** [comment]
Thanks!
