### ISSUE TITLE
Websocket API missing candlesticks stream endpoints

### ISSUE THREAD

**Issue by xiao99xiao** [bitbankinc/bitbank-api-docs#3]
The current pubnub API provides a candlesticks stream like `candlestick_btc_jpy` , so it would be great if the new websocket API also supports that. It's very useful for advanced traders.

## Current Behavior
There's no candlesticks stream support in new websocket API at the moment.

**Comment by daiki-ojima** [comment]
@xiao99xiao Thanks for the feedback.

We will consider your proposal.

**Comment by soichirokodama** [comment]
Thanks for raising the issue.

For future feature requests, please contact us from the support page.

We'll investigate it using provided information.

https://support.bitbank.cc/hc/ja/requests/new
