### ISSUE TITLE
Maintaining local order book

### ISSUE THREAD

**Issue by bitkanpeki** [bitbankinc/bitbank-api-docs#36]
I'm having a hard time to maintain a local order book using the DIFF updates. 

There seems the depth_whole websocket sometimes is missing a depth_diff update or adding a price that is NOT included in the depth_diff updates. Is it possible the server is not sending some updates?

I'm using socket.io client 2.4.0 to listen to the websocket.

Anyone has been able to maintain a correct local order book?

**Comment by mojamonja** [comment]
@bitkanpeki Thanks for raising the issue.
I think socket.io v2.x is OK for now.
We recently updated our exchange system on Sep. 27 2021, are you still having that problem?
