### ISSUE TITLE
2000ms create order delay

### ISSUE THREAD

**Issue by eckozen84** [bitbankinc/bitbank-api-docs#38]
All my new orders, whether it is a limit or market order, have approximately 2000ms delay. If I submit 5 orders simultaneously (asynchronously), it will take approx ~10000ms for all orders to be processed (2000ms one after the other). This pattern leads me to believe it is no coincidence. I am using the timestamp on the order response to confirm this.

I am located in Tokyo and previously my orders have approximately ~100ms latency. 

It would appear your API queues any requests and processes them 2000ms apart. Surely this cannot be the correct implementation? 2000ms is just too slow for high-frequency trading or market making.

**Comment by mojamonja** [comment]
@eckozen84 Thanks for raising the issue.
It seems this is not related to api-docs but environmental or per-user.
Would you contact us from the support page?
We'll investigate it using provided information.

https://support.bitbank.cc/hc/ja/requests/new

* Please select your issue below → `お取引・資産について` (about trading or asset)
* 問い合わせ内容（お取引・資産について）(category of issue) → `取引所での取引について` (about spot trading)
* 通貨種別 (asset) → something you have ordered
* Description → please include your account id (something like ABCD12345), that is required to investigate per-user issue
* 日時 → the date/time that you found delaying
* 該当する全ての注文ID → some example order ids that you found delaying

Thanks.

**Comment by eckozen84** [comment]
@mojamonja You are correct, I have no issues when using Bitbank API. It is currently an issue with a library I am using called CCXT.

Thank you.
