### ISSUE TITLE
Constantly getting disconnected from websocket after a few minutes

### ISSUE THREAD

**Issue by eckozen84** [bitbankinc/bitbank-api-docs#4]
I can connect and receive real-time messages for a few minutes before the server disconnects me with reason "io server disconnect". I use nodeJS with socket.io-client and my sample code is below.

I have also test with wscat and get the same result - "disconnected (code: 1005)" after a few minutes.

```
        const io = require('socket.io-client');
        const bitbank = io('wss://stream.bitbank.cc', {
            transports: ['websocket']
        });
        bitbank.on('connect', () => {
            bitbank.emit('join-room', 'depth_diff_btc_jpy');
        });
        bitbank.on('message', (data) => {
            console.log(data)
        });
        bitbank.on('disconnect', (data) => {
            console.log(data);
        });
```

**Comment by gusutabopb** [comment]
I have the same issue. 
Even with proper pinging, the connection is closed from the server side (code 1005) after about 300 seconds (5 minutes).

Probably irrelevant, but I have tried from Golang, Python and wscat and always get the same result.

**Comment by unknown12345678** [comment]
I've noticed the same. Exactly 5 minutes after connection is opened, it is closed by the server.

**Comment by gusutabopb** [comment]
Also, the exact same behavior happens on the browser. After 300s, the connection is closed. On the picture below, the connection started at 17:55:31 and got closed by the server at 18:01:31.
<img width="1042" alt="Screen Shot 2019-10-15 at 18 01 27" src="https://user-images.githubusercontent.com/4231387/66817130-2e17c580-ef76-11e9-9747-1769895982a2.png">

**Comment by daiki-ojima** [comment]
Our websocket connections can be destroyed by server periodically (currently every 5 minutes) for purpose of refreshing malicious connections.

socket.io-client has `reconnection` option. and default is true.
but, doesn't work.
So, it is necessary to implement reconnection periodically client side.

```javascript
const PERIODIC_RECONNECT_INTERVAL = 1000 * 60 * 5;

setInterval(() => {
  bitbank.on('connect', () => {
    bitbank.emit('join-room', 'depth_diff_btc_jpy');
  });
}, PERIODIC_RECONNECT_INTERVAL);
```

**Comment by unknown12345678** [comment]
@daiki-ojima that should not be the proper implementation. I rely on real-time, up-to-date data to execute trades, if I am reconnecting every 5 minutes then I am missing data in between reconnects.

**Comment by unknown12345678** [comment]
@daiki-ojima Even if I use wscat (which is your preferred method) and still get dropped every 5 minutes - why is that considered a malicious connection?

**Comment by gusutabopb** [comment]
@daiki-ojima Thanks for the reply.

As pointed out by @unknown12345678, this implementation doesn't make much sense.
There's always the risk of data leakage between reconnects (which will take at least a few milliseconds). I have never seen any cryptocurrency exchange that has such behavior. 

Bitbank Pubnub didn't have that, Bitflyer (even their Socket.IO stream) doesn't have that, Bitmex doesn't have that, Quoine doesn't have that either. Therefore I don't really understand he "malicious connections" reason. (There are probably many better ways to solve this, such as rate limiting number of connection attempts per IP, per given time slot, etc).

Trying to avoid data leakage by always having multiple connections and/or double checking with the REST API adds a LOT of complexity on the client side (and extra burden on the server for all the duplicated connections / API calls).

I ask you to please reconsider this pointless server-side disconnection every 300 seconds.

**Comment by daiki-ojima** [comment]
@gusutabopb @unknown12345678  Thanks for the feedback.

We understand that problems with our stream-api implementation.
In addition, based on the feedback, we will review the specifications and improve stream-api implementation.

**Comment by unknown12345678** [comment]
Upon further testing, I can see now the disconnect interval is exactly 3600 sec (1 hour). Can we not extend this to a 24 hour interval? For example, binance forces a server disconnect only once every 24 hours.

**Comment by AnnuRArya** [comment]
Hi,
I have similar issue, did somebody find any solutions?
Also can we get messages after socket is closed with 1005 status code?

**Comment by gusutabopb** [comment]
@AnnuRArya There is no solution as the connection is closed from the server side on purpose to ["refresh malicious connections"](https://github.com/bitbankinc/bitbank-api-docs/issues/4#issuecomment-542563070). The only solution would be for Bitbank to listen to users and stop doing this non-sensical disconnection. The situation has improved a bit (5 minutes -> 60 minutes), so perhaps a bit more pushing will make them change it to 24 hours (or infinity) as most other crypto exchanges.


> Also can we get messages after socket is closed with 1005 status code?

I don't think so.

**Comment by unknown12345678** [comment]
> Hi,
> I have similar issue, did somebody find any solutions?
> Also can we get messages after socket is closed with 1005 status code?

Unfortunately, there is no other option except to reconnect upon disconnection by the server. The worst part is they've changed how often they update their REST API order book (every 10-15 seconds) so there is no way to fill in the data loss between reconnects. 

Please, Bitbank, please change it to 24 hours or unlimited. There is no reasonable exchange in the world, be it crypto, derivatives, commodities or stock that disconnects you every hour.

**Comment by unknown12345678** [comment]
@daiki-ojima Is there any progress on this? I am constantly getting ping timeouts and transport close errors from reconnecting after getting disconnected constantly. It is impossible to trade like this.

**Comment by eckozen84** [comment]
@daiki-ojima please, is there any update on this? still having constant disconnects every day. Haven't been able to trade for months via api.

**Comment by lnguyen-lc** [comment]
@eckozen84 
I checked with my Mac Terminal and it disconnected after 30secs not even 1 hour

**Comment by bitkanpeki** [comment]
Any updates on this? I'm getting disconnected after a few seconds as well.

**Comment by koiizuka** [comment]
As described in [info](https://github.com/bitbankinc/bitbank-api-docs/blob/master/public-stream.md#general-wss-information
) 6 hours auto disconnection specification is abolished.

A connection is not disconnected unless an error occurs.

Sometimes, We receive inquiry of 30sec disconnection. This problem occurs in Ping/Pong Timeout from difference of Socket.IO version.

It is also resolved because of Socket.IO version upgrade and socket.io-client >= v4 works well.

Since allowEIO3 flag is true, you can currently connect even with EIO=3.
But, We recommend connection with EIO=4 Because we will make allowEIO3 deprecated in the future
