### ISSUE TITLE
Email verification necessary for withdrawal?

### ISSUE THREAD

**Issue by CJNA** [bitbankinc/bitbank-api-docs#52]
Issue tracker is **ONLY** used for reporting bugs.

## Current Behavior

Current behavior for withdrawal requires additional step from an account, to verify through email. 
Is this step necessary or is there a way to avoid this? We are already utilizing private API key to issue a withdrawal request and I feel it doesn't make sense to have an additional step for withdrawal

## Steps to Reproduce

1.
2.
3.

**Comment by soichirokodama** [comment]
@CJNA 
Thanks for raising the issue.
It seems not a bug but a feature request.
Would you contact us from the support page?
We'll investigate it using provided information.

https://support.bitbank.cc/hc/ja/requests/new

**Comment by CJNA** [comment]
Will do. 
Sorry was unaware that this is only for bug reporting
