### ISSUE TITLE
"sequenceID" key in real-time messages

### ISSUE THREAD

**Issue by eckozen84** [bitbankinc/bitbank-api-docs#6]
Could you provide further clarification regarding this "sequenceID"?

I find inconsistencies when comparing the sequenceID of a whole book message versus a diff book message. 

For example:
whole_sequenceID < diff_sequenceID 
whole_timestamp > diff_timestamp

This doesn't make sense.

**Comment by soichirokodama** [comment]
@eckozen84 
Sorry for the late reply.

Added description of order book including sequenceID.

Please check below.
https://github.com/bitbankinc/bitbank-api-docs/blob/master/public-stream.md#how-to-manage-a-local-order-book-correctly
