### ISSUE TITLE
Automatic cancellation of post only orders

### ISSUE THREAD

**Issue by CJNA** [bitbankinc/bitbank-api-docs#68]
Issue tracker is **ONLY** used for reporting bugs.

When I issue a post only purchase request, it often gets cancelled automatically. Any reason behind this behavior?

## Expected Behavior

Do not expect order to be cancelled until explicitly issued cancel.

## Current Behavior

Post only orders get cancelled without explicit control.

## Steps to Reproduce

1. Issue a request via 
`bitbank_private_client.order(
                target_currency + '_' + 'jpy', # ペア
                buy_price, # 価格 (成行注文の場合は None にする)
                target_amount, # 注文枚数
                'buy', # 注文サイド (buy|sell)
                'limit', # 注文タイプ (limit|market|stop|stop_limit)
                # 以降は任意の引数
                True, # post_only 注文、デフォは False, None も可能で Falseと同じ挙動
                None # trigger_price 逆指値などのトリガー価格
            )`
2. Observe order being cancelled by ```
bitbank_private_client.get_order(
                target_currency + '_' + 'jpy', # ペア
                cur_order_id,
            )
```
3.

## Context (Environment)
<!--- How has this issue affected you? What are you trying to accomplish? -->
This is preventing me from establishing a arbitrage routine that involves issuing purchase and cancellation for given price of currency. 

<!--- Providing context helps us come up with a solution that is most useful in the real world -->

<!--- Provide a general summary of the issue in the Title above -->
Post-only Order cancellation without consent

## Detailed Description
<!--- Provide a detailed description of the change or addition you are proposing -->

**Comment by mojamonja** [comment]
Hi @CJNA , Thanks for creating this issue!
I think its cancellation is by our exchange's spec, as post only order is by definition "to be maker or cancel."
Would you check the price parameter is/was not-taking price compared to the best ask/bid price at the order time, or try post_only=false if it's also OK to be taker?

**Comment by mojamonja** [comment]
Hi @CJNA, did my explanation make sense? I hope so and I'll close this issue.
Feel free to reopen or create a new issue if you have more questions 😉

**Comment by CJNA** [comment]
Oh no I figured that was the case.
Thanks for the detailed explanation!

Feel free to close this case
