### ISSUE TITLE
doc looks not maintained

### ISSUE THREAD

**Issue by akiradeveloper** [bitbankinc/bitbank-api-docs#75]
I wrote this program to check the response from the public API.

```rust
    async fn test() -> anyhow::Result<()> {
        let cli = reqwest::Client::new();
        let url = "https://public.bitbank.cc/xrp_jpy/ticker";
        let response: serde_json::Value = cli.get(url).send().await?.json().await?;
        dbg!(&response);
        Ok(())
    }
```

and the raw JSON response is here

```rust
[src/lib.rs:41] &response = Object {
    "data": Object {
        "buy": String("67.690"),
        "high": String("68.235"),
        "last": String("67.700"),
        "low": String("66.104"),
        "open": String("66.390"),
        "sell": String("67.691"),
        "timestamp": Number(1680929665091),
        "vol": String("8431091.4545"),
    },
    "success": Number(1),
}
```

According to the doc (https://github.com/bitbankinc/bitbank-api-docs/blob/master/public-api.md#general-api-information), the success field should be 0 when the response is successful. So what does the success 1 mean?

The doc also says

> For GET endpoints, parameters must be sent as a query string.

but no example in the doc contains parameters in the query string but in the path.

Any spec change?

**Comment by junderw** [comment]
Thanks for the issue! I have fixed the issue in a PR. Please let me know if there's anything else.
