### ISSUE TITLE
`/user/spot/trade_history` is Broken

### ISSUE THREAD

**Issue by xiao99xiao** [bitbankinc/bitbank-api-docs#8]
After the maintenance in 12/9 morning, `/user/spot/trade_history` is broken. 

Before the maintenance, a request without an `order_id ` parameter works fine.

After it, a request without an `order_id ` parameter has a 50% chance to fail, getting an error response: `{ success: 0, data: { code: 40013 } }` , while `40013` means `Invalid order id` . So it seems `order_id` becomes mandatory randomly for this API.

**Comment by daiki-ojima** [comment]
@xiao99xiao 

Thank you for the bug report.

It did not reproduce in our environment.
So, Please contact us from the support page for more information.
We will analysis according to individual user data.

https://support.bitbank.cc/hc/ja/requests/new

**Comment by xiao99xiao** [comment]
@daiki-ojima 

Actually we are receiving multiple feedback from our users about this issue, and we could reproduce it but very randomly. I guess It's possibly because of an incomplete deployment, therefore some server works some don't.

So anyway I'm not going to the submit it on the support page since I can't even reproduce it 100%. But some of our users are suffering from this issue, so it would be great if you could look into it again, or, maybe we could keep this open and see if anyone else would encounter the same issue 😊

**Comment by xiao99xiao** [comment]
All of our users are reporting the issue being resolved. I'll close this issue for now.
