### ISSUE TITLE
Question about post_only flag

### ISSUE THREAD

**Issue by akiradeveloper** [bitbankinc/bitbank-api-docs#80]
The post_only flag in fetch order info API (and others) says it is only presents if type = limit. Does this mean the flag is omitted otherwise? If not then why not type isn't "or null"?

> whether Post Only or not (present only if type = limit)

The same flag in the parameter of the create new order API says meanwhile

> true can be specified only if type = limit. default false

I feel like the semantics is more convincing with the latter.

Which is correct?

**Comment by soichirokodama** [comment]
> Does this mean the flag is omitted otherwise?

Yes, it means the flag is omitted.

> If not then why not type isn't "or null"?

Because there is no post_only in the response content.


post_only=true can be specified only when the order type is limit.  
And if you don't specify anything for post_only, it will be requested with the value false(default false).

**Comment by akiradeveloper** [comment]
> Because there is no post_only in the response content.

Is this true?

I found a post_only flag in the response from fetch order API https://github.com/bitbankinc/bitbank-api-docs/blob/master/rest-api.md#fetch-order-information

**Comment by soichirokodama** [comment]
post_only is present in the response only when type = limit.

> whether Post Only or not (present only if type = limit)

And I understand what you are saying.

Does that mean that the Type should express that?

**Comment by soichirokodama** [comment]
> post_only doesn't appear in response unless the type is limit.

This is correct, so I'll fix it along with what other issues have pointed out.

**Comment by soichirokodama** [comment]
Corresponded to the contents of the issue.
And fixed some mistakes in the documentation.

https://github.com/bitbankinc/bitbank-api-docs/pull/86
