### ISSUE TITLE
create order API: trigger_price should be optional?

### ISSUE THREAD

**Issue by akiradeveloper** [bitbankinc/bitbank-api-docs#81]
The API doc says the field is always included but I think it is only present when the request include it.

When I submit a simple buy limit order, the response doesn't have the field.

**Comment by soichirokodama** [comment]
As you pointed out, it is only included in the response when type=stop or stop_limit.

I'll fix the documentation.

**Comment by soichirokodama** [comment]
Corresponded to the contents of the issue.
And fixed some mistakes in the documentation.

https://github.com/bitbankinc/bitbank-api-docs/pull/86
