### ISSUE TITLE
timestamp in candlestick API is actually a number

### ISSUE THREAD

**Issue by akiradeveloper** [bitbankinc/bitbank-api-docs#82]
The doc gives `string[]` type to a candlestick

![スクリーンショット 2023-04-12 19 49 05](https://user-images.githubusercontent.com/785824/231435808-7dcdc666-e8a5-4d0f-8c38-2243c490d497.png)

```
{
  "success": 1,
  "data": {
    "candlestick": [
      {
        "type": "string",
        "ohlcv": [
          [
            "string"
          ]
        ]
      }
    ]
  }
}
```

but the response from the API server is actually 5 strings followed by a timestamp as a number. Below is a debug print of `serde_json::Value`. I think the doc is not updated.

```
[bitbank-api/src/public/candlestick.rs:74] &resp = Response {
    candlestick: [
        Object {
            "ohlcv": Array [
                Array [
                    String("44.588"),
                    String("44.610"),
                    String("44.160"),
                    String("44.400"),
                    String("7787357.6803"),
                    Number(1672531200000),
                ],
```

**Comment by soichirokodama** [comment]
Thank you for pointing this out.

You're right, I'll fix the documentation.

**Comment by soichirokodama** [comment]
Corresponded to the contents of the issue.
And fixed some mistakes in the documentation.

https://github.com/bitbankinc/bitbank-api-docs/pull/86
