### ISSUE TITLE
Websocket API "Request" documentation

### ISSUE THREAD

**Issue by kartik1205** [bitbankinc/bitbank-api-docs#83]
Hi, I am unable to find any API doc that specifies what should be the request param in order to subscribe and unsubscribe channels on the Websockets. Could you please provide the same?
Also are there any error codes/messages generated if the request param is incorrect? For example, would subscribing to incorrect ticker_pair generate any specified response that denotes incorrect request params?
Thanks!

**Comment by koiizuka** [comment]
Websocket docs is here: https://github.com/bitbankinc/bitbank-api-docs/blob/master/public-stream.md

If you want to subscribe BTC/JPY ticker, send message `42["leave-room", "ticker_btc_jpy"]`.
And unsubcribe pattern message is `42["leave-room",  "ticker_btc_jpy"]`.

We implement websocket server with [Socket.IO](https://socket.io/).
So we recommend you implement client application with Socket.IO also.

If you implement client application with simple websocket libraries, please don't forget to [ping / pong heartbeat](https://socket.io/docs/v4/engine-io-protocol/#heartbeat) message implementation
