### ISSUE TITLE
Unit of timestamp in parameters

### ISSUE THREAD

**Issue by akiradeveloper** [bitbankinc/bitbank-api-docs#84]
fetch-active-orders API has parameter called `since` which is described to take unix timestamp but what is the unit?

Timestamp in responses are written as ms but the none of the request parameters doesn't clarify it.

May I assume they are in ms as well? or are they in sec since the unit isn't specified?

**Comment by soichirokodama** [comment]
The unit is milliseconds.
I'll fix the Docs.

**Comment by soichirokodama** [comment]
Corresponded to the contents of the issue.
And fixed some mistakes in the documentation.

https://github.com/bitbankinc/bitbank-api-docs/pull/86
