### ISSUE TITLE
Ws stream for private data?

### ISSUE THREAD

**Issue by kartik1205** [bitbankinc/bitbank-api-docs#89]
is there any websocket stream for private data just like you have one for public data?

**Comment by koiibb** [comment]
There is not private stream yet.
We are aware of the request for private stream and will develop it in the future.

**Comment by kartik1205** [comment]
Right sure.
So another question is that since we have to rely on rest client for private data, is there any limitation on those rest calls?

**Comment by koiibb** [comment]
@kartik1205 
REST API limitation is described here
https://github.com/bitbankinc/bitbank-api-docs/blob/master/rest-api.md#rate-limit

> We usually limits QUERY requests to 10 calls per second and UPDATE requests to 6 calls per second.
