### ISSUE TITLE
Withdraw history or check withdraw

### ISSUE THREAD

**Issue by merlinkory** [bitbankinc/bitbank-api-docs#9]
When i making withdraw BTC via API, i want to check status of this withdraw in furture, can i do it? or may be i have some way to get withdraw history via API?

**Comment by soichirokodama** [comment]
@merlinkory 
Sorry for the late reply.

Withdrawal history API was added recently.

See below for details.
https://github.com/bitbankinc/bitbank-api-docs/blob/master/rest-api.md#fetch-withdrawal-history
