### ISSUE TITLE
Clarification on /user/spot/cancel_orders API

### ISSUE THREAD

**Issue by CHANist** [bitbankinc/bitbank-api-docs#90]
From the documentation, it does not mention the maximum array size of `order_ids`. 
So can I assume the system can receive a very long order_ids, i.e. length is bounded by 2,147,483,647? 
Or I should split it to multiple request, if so, by how much?

**Comment by soichirokodama** [comment]
Sorry for my late reply.
Up to 30 ids can be specified for `order_ids`.
I'll make a note of that in the docs as well.

**Comment by CHANist** [comment]
May I also ask for `GET /user/spot/active_orders` API, if I does not supply count, 
can I retrieve all active orders?

**Comment by soichirokodama** [comment]
Yes, you can get all active orders if you don't specify a count.
