### ISSUE TITLE
Clarification of RateLimit scope

### ISSUE THREAD

**Issue by CHANist** [bitbankinc/bitbank-api-docs#91]
From the documentation, we can see that `We usually limits QUERY requests to 10 calls per second `. 

However, it is not clear to me which categories as QUERY request and which not. 
1. Is the request per user (i.e. only applies to auth request?) or per ip? 
2. If per IP, then does `/spot/pairs` and `/spot/status` include in QUERY request? 
3. How about public-api? Does it excluded from the limit?

**Comment by soichirokodama** [comment]
We will answer your questions.

1. As explained in [the documentation here](https://github.com/bitbankinc/bitbank-api-docs/blob/master/rest-api.md#rate-limit), the limit is per user, not per IP.
2. Limits are per user, but both are included in the QUERY request.
3. public-api is unlimited.

**Comment by herbert-okx** [comment]
During testing, we found that when we query API more than expected, it throws errorCode 20001, which means Authentication failed api authorization, which seems not the case. When I slower my rate limiter, things seem to work. 
Can you confirm this is an API issue? 

Moreover, just wonder, if we can buy throttling limit.
