### ISSUE TITLE
Duplicate error codes in errors.md

### ISSUE THREAD

**Issue by AkiraMiyakoda** [bitbankinc/bitbank-api-docs#97]
`errors.md` has duplicate error codes:
https://github.com/bitbankinc/bitbank-api-docs/blob/38d6d7c6f486c793872fd4b4087a0d090a04cd0a/errors.md?plain=1#L179-L180

Probably the latter should be 70023.

**Comment by soichirokodama** [comment]
Thank you for pointing this out.  
I will fix the Docs.

**Comment by soichirokodama** [comment]
It's late, but I fixed it with the pull request below.  
https://github.com/bitbankinc/bitbank-api-docs/pull/99
